
name: hydra-eo
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - rasterio
  - xarray
  - pyproj
  - shapely
  - scikit-learn
  - matplotlib
  - rtree
  - pip
  - pip:
      - jupyter
